# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
aerial_sdk_version: 25-3-cubb
ru_emulator:

  ul_core_list: [2,3,4,5,6,7,8,9,10,11]
  dl_core_list: [12,13,14,15,16,17,18,19,20,21]
  dl_rx_core_list: [68,70,72,74,76,78,80,82,84,86,88,90,92,94,96,98,100,102,104,106] #Valid only if enable_dl_proc_mt is 1

  # nvlog name: the nvlog instance name
  nvlog_name: ru

  # Send cell config/start/stop request via OAM command
  oam_cell_ctrl_cmd: 0

  low_priority_core: 23

  # PCI Address of NIC interface used
  nics:
    - nic_interface: 'b5:00.0'
    # - nic_interface: 'b5:00.1'
  # MAC address of cuPHYController port in use
  peers:
    # - peerethaddr: 48:b0:2d:a6:02:32 #e200-r750-1 (P0)
    # - peerethaddr: 48:b0:2d:63:86:2c #e200-r750-2 (P0)
    # - peerethaddr: 48:b0:2d:a6:2e:74 #k1-r750-01(RoyB) (P0)
    # - peerethaddr: 48:b0:2d:a6:28:02 #k1-r750-02(RoyB) (P0)
    # - peerethaddr: 48:b0:2d:a6:0f:f2 #e200-r750-04 (P0)
    # - peerethaddr: 48:b0:2d:63:6a:6c #munich-aerial-mec (P0)
    # - peerethaddr: 48:b0:2d:a6:28:86 #munich-aerial-cn (P0)
    # - peerethaddr: 48:b0:2d:a6:00:a6 #k1-r750-07(RoyB) (P0)
    # - peerethaddr: 94:6d:ae:c7:6c:3e #gh-qct-cg1-qs-01 (P0)
    # - peerethaddr: 94:6d:ae:f5:a1:a6 #gh-smc-cg1-qs-01 (P0)
    # - peerethaddr: 94:6d:ae:f5:a6:1a #gh-smc-cg1-qs-02 (P0)
    # - peerethaddr: 94:6d:ae:f5:a7:96 #gh-smc-cg1-qs-03 (P0)
    - peerethaddr:  48:b0:2d:a6:27:d6 #k1-r750-08(RoyB) (P0)
    #- peerethaddr:  94:6d:ae:f5:a6:8c #gh-smc-cg1-qs-07


  cell_configs:
    -
      name: "Cell1"
      eth: "20:04:9B:9E:27:A3"
      eAxC_UL: [8,0,1,2]
      eAxC_DL: [8,0,1,2]
      eAxC_prach_list: [15,7,0,1]
      eAxC_srs_list: [9,3,5,6]
      dl_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      ul_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      fs_offset_dl: 0
      exponent_dl: 4
      ref_dl: 0
      ru_type: 3
      peer: 0
      nic: 0
      vlan: 2
      pcp: 7
    -
      name: "Cell2"
      eth: "26:04:9D:9E:29:B3"
      eAxC_UL: [1,2,4,9]
      eAxC_DL: [1,2,4,9]
      eAxC_prach_list: [5,6,7,10]
      eAxC_srs_list: [5,6,7,10]
      dl_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      ul_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      fs_offset_dl: 0
      exponent_dl: 4
      ref_dl: 0
      ru_type: 3
      peer: 0
      nic: 0
      vlan: 2
      pcp: 7
    -
      name: "Cell3"
      eth: "20:34:9A:9E:29:B3"
      eAxC_UL: [1,2,4,9]
      eAxC_DL: [1,2,4,9]
      eAxC_prach_list: [5,6,7,10]
      eAxC_srs_list: [5,6,7,10]
      dl_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      ul_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      fs_offset_dl: 0
      exponent_dl: 4
      ref_dl: 0
      ru_type: 3
      peer: 0
      nic: 0
      vlan: 2
      pcp: 7
    -
      name: "Cell4"
      eth: "22:34:9C:9E:29:A3"
      eAxC_UL: [0,1,2,3]
      eAxC_DL: [0,1,2,3]
      eAxC_prach_list: [5,6,7,10]
      eAxC_srs_list: [5,6,7,10]
      dl_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      ul_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      fs_offset_dl: 0
      exponent_dl: 4
      ref_dl: 0
      ru_type: 3
      peer: 0
      nic: 0
      vlan: 2
      pcp: 7
    -
      name: "Cell5"
      eth: "20:04:9B:9E:27:05"
      eAxC_UL: [0,1,2,3]
      eAxC_DL: [0,1,2,3]
      eAxC_prach_list: [5,6,7,10]
      eAxC_srs_list: [5,6,7,10]
      dl_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      ul_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      fs_offset_dl: 0
      exponent_dl: 4
      ref_dl: 0
      ru_type: 3
      peer: 0
      nic: 0
      vlan: 2
      pcp: 7
    -
      name: "Cell6"
      eth: "20:04:9B:9E:27:06"
      eAxC_UL: [0,1,2,3]
      eAxC_DL: [0,1,2,3]
      eAxC_prach_list: [5,6,7,10]
      eAxC_srs_list: [5,6,7,10]
      dl_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      ul_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      fs_offset_dl: 0
      exponent_dl: 4
      ref_dl: 0
      ru_type: 3
      peer: 0
      nic: 0
      vlan: 2
      pcp: 7
    -
      name: "Cell7"
      eth: "20:04:9B:9E:27:07"
      eAxC_UL: [0,1,2,3]
      eAxC_DL: [0,1,2,3]
      eAxC_prach_list: [5,6,7,10]
      eAxC_srs_list: [5,6,7,10]
      dl_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      ul_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      fs_offset_dl: 0
      exponent_dl: 4
      ref_dl: 0
      ru_type: 3
      peer: 0
      nic: 0
      vlan: 2
      pcp: 7
    -
      name: "Cell8"
      eth: "20:04:9B:9E:27:08"
      eAxC_UL: [0,1,2,3]
      eAxC_DL: [0,1,2,3]
      eAxC_prach_list: [5,6,7,10]
      eAxC_srs_list: [5,6,7,10]
      dl_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      ul_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      fs_offset_dl: 0
      exponent_dl: 4
      ref_dl: 0
      ru_type: 3
      peer: 0
      nic: 0
      vlan: 2
      pcp: 7
    -
      name: "Cell9"
      eth: "20:04:9B:9E:27:09"
      eAxC_UL: [0,1,2,3]
      eAxC_DL: [0,1,2,3]
      eAxC_prach_list: [5,6,7,10]
      eAxC_srs_list: [5,6,7,10]
      dl_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      ul_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      fs_offset_dl: 0
      exponent_dl: 4
      ref_dl: 0
      ru_type: 3
      peer: 0
      nic: 0
      vlan: 2
      pcp: 7
    -
      name: "Cell10"
      eth: "20:04:9B:9E:27:0A"
      eAxC_UL: [0,1,2,3]
      eAxC_DL: [0,1,2,3]
      eAxC_prach_list: [5,6,7,10]
      eAxC_srs_list: [5,6,7,10]
      dl_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      ul_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      fs_offset_dl: 0
      exponent_dl: 4
      ref_dl: 0
      ru_type: 3
      peer: 0
      nic: 0
      vlan: 2
      pcp: 7
    -
      name: "Cell11"
      eth: "20:04:9B:9E:27:0B"
      eAxC_UL: [0,1,2,3]
      eAxC_DL: [0,1,2,3]
      eAxC_prach_list: [5,6,7,10]
      eAxC_srs_list: [5,6,7,10]
      dl_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      ul_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      fs_offset_dl: 0
      exponent_dl: 4
      ref_dl: 0
      ru_type: 3
      peer: 0
      nic: 0
      vlan: 2
      pcp: 7
    -
      name: "Cell12"
      eth: "20:04:9B:9E:27:0C"
      eAxC_UL: [0,1,2,3]
      eAxC_DL: [0,1,2,3]
      eAxC_prach_list: [5,6,7,10]
      eAxC_srs_list: [5,6,7,10]
      dl_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      ul_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      fs_offset_dl: 0
      exponent_dl: 4
      ref_dl: 0
      ru_type: 3
      peer: 0
      nic: 0
      vlan: 2
      pcp: 7
    -
      name: "Cell13"
      eth: "20:04:9B:9E:27:0D"
      eAxC_UL: [0,1,2,3]
      eAxC_DL: [0,1,2,3]
      eAxC_prach_list: [5,6,7,10]
      eAxC_srs_list: [5,6,7,10]
      dl_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      ul_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      fs_offset_dl: 0
      exponent_dl: 4
      ref_dl: 0
      ru_type: 3
      peer: 0
      nic: 0
      vlan: 2
      pcp: 7
    -
      name: "Cell14"
      eth: "20:04:9B:9E:27:0E"
      eAxC_UL: [0,1,2,3]
      eAxC_DL: [0,1,2,3]
      eAxC_prach_list: [5,6,7,10]
      eAxC_srs_list: [5,6,7,10]
      dl_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      ul_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      fs_offset_dl: 0
      exponent_dl: 4
      ref_dl: 0
      ru_type: 3
      peer: 0
      nic: 0
      vlan: 2
      pcp: 7
    -
      name: "Cell15"
      eth: "20:04:9B:9E:27:0F"
      eAxC_UL: [0,1,2,3]
      eAxC_DL: [0,1,2,3]
      eAxC_prach_list: [5,6,7,10]
      eAxC_srs_list: [5,6,7,10]
      dl_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      ul_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      fs_offset_dl: 0
      exponent_dl: 4
      ref_dl: 0
      ru_type: 3
      peer: 0
      nic: 0
      vlan: 2
      pcp: 7
    -
      name: "Cell16"
      eth: "20:04:9B:9E:27:10"
      eAxC_UL: [0,1,2,3]
      eAxC_DL: [0,1,2,3]
      eAxC_prach_list: [5,6,7,10]
      eAxC_srs_list: [5,6,7,10]
      dl_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      ul_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      fs_offset_dl: 0
      exponent_dl: 4
      ref_dl: 0
      ru_type: 3
      peer: 0
      nic: 0
      vlan: 2
      pcp: 7
    -
      name: "Cell17"
      eth: "20:04:9B:9E:27:11"
      eAxC_UL: [0,1,2,3]
      eAxC_DL: [0,1,2,3]
      eAxC_prach_list: [5,6,7,10]
      eAxC_srs_list: [5,6,7,10]
      dl_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      ul_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      fs_offset_dl: 0
      exponent_dl: 4
      ref_dl: 0
      ru_type: 3
      peer: 0
      nic: 0
      vlan: 2
      pcp: 7
    -
      name: "Cell18"
      eth: "20:04:9B:9E:27:12"
      eAxC_UL: [0,1,2,3]
      eAxC_DL: [0,1,2,3]
      eAxC_prach_list: [5,6,7,10]
      eAxC_srs_list: [5,6,7,10]
      dl_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      ul_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      fs_offset_dl: 0
      exponent_dl: 4
      ref_dl: 0
      ru_type: 3
      peer: 0
      nic: 0
      vlan: 2
      pcp: 7
    -
      name: "Cell19"
      eth: "20:04:9B:9E:27:13"
      eAxC_UL: [0,1,2,3]
      eAxC_DL: [0,1,2,3]
      eAxC_prach_list: [5,6,7,10]
      eAxC_srs_list: [5,6,7,10]
      dl_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      ul_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      fs_offset_dl: 0
      exponent_dl: 4
      ref_dl: 0
      ru_type: 3
      peer: 0
      nic: 0
      vlan: 2
      pcp: 7
    -
      name: "Cell20"
      eth: "20:04:9B:9E:27:14"
      eAxC_UL: [0,1,2,3]
      eAxC_DL: [0,1,2,3]
      eAxC_prach_list: [5,6,7,10]
      eAxC_srs_list: [5,6,7,10]
      dl_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      ul_iq_data_fmt: {comp_meth: 1, bit_width: 9}
      fs_offset_dl: 0
      exponent_dl: 4
      ref_dl: 0
      ru_type: 3
      peer: 0
      nic: 0
      vlan: 2
      pcp: 7
  tti: 500
  dl_up_sanity_check: 1
  max_sect_stats: 0
  dl_bfw_validation: 1
  ul_bfw_validation: 1
  validate_dl_timing: 1
  timing_histogram: 0
  timing_histogram_bin_size: 1000 # in nanoseconds
  dl_approx_validation: 0
  enable_mmimo: 0
  enable_beam_forming: 0
  enable_cplane_worker_tracing: 0
  dl_warmup_slots: 2000
  dlc_tb: 0
  fix_beta_dl: 1
  payload_validation: 1
  enable_dl_proc_mt: 0 #Enable multi-threaded processing for dl_proc (receive/process)
  aerial_fh_txq_size: 4096
  aerial_fh_rxq_size: 2048
  aerial_fh_tx_request_num: 32
  aerial_fh_dpdk_thread: 1
  aerial_fh_pdump_client_thread: -1
  aerial_fh_accu_tx_sched_res_ns: 500 #Flag applicable only for CX6-DX : BF3/CX7 HW and beyond support accurate send scheduling directly on timestamp, for CX6-DX this is implemented via software emulation
  aerial_fh_dpdk_file_prefix: "ru_emulator"
  aerial_fh_per_rxq_mempool : 0
  aerial_fh_cpu_mbuf_pool_size_per_rxq: 32768 #Applies only if aerial_fh_per_rxq_mempool is set to 1
  aerial_fh_cpu_mbuf_pool_rx_size: 262144 #Applies to rx as well if aerial_fh_per_rxq_mempool is set to 0
  aerial_fh_cpu_mbuf_pool_tx_size: 262144 #Applies to rx as well if aerial_fh_per_rxq_mempool is set to 0
  aerial_fh_split_rx_tx_mempool: 1
  aerial_fh_mtu: 1514
  enable_srs_eaxcid_pacing: 0
  # SRS eAxC ID Pacing Configuration (only required if enable_srs_eaxcid_pacing: 1)
  srs_pacing_s3_srs_symbols: 2        # SRS symbols in slots *3 (3,13,23,...) - symbols at end of slot
  srs_pacing_s4_srs_symbols: 0        # SRS symbols in slots *4 (4,14,24,...)
  srs_pacing_s5_srs_symbols: 0        # SRS symbols in slots *5 (5,15,25,...)
  srs_pacing_eaxcids_per_tx_window: 4 # eAxC IDs per transmission window
  srs_pacing_eaxcids_per_symbol: 64   # Total eAxC IDs per symbol
  debug_u_plane_prints: 0
  debug_u_plane_threshold: 20
  oran_timing_info:
    dl_c_plane_timing_delay: 470
    dl_c_plane_window_size: 51
    ul_c_plane_timing_delay: 336
    ul_c_plane_window_size: 51
    dl_u_plane_timing_delay: 345
    dl_u_plane_window_size: 51
    ul_u_plane_tx_offset: 231
    ul_u_plane_tx_offset_srs: 231
  oran_beam_id_info: {static_beam_id_start: 1, static_beam_id_end: 16527, dynamic_beam_id_start: 16528, dynamic_beam_id_end: 32767}
  ecpri_hdr_cfg_test: {enable: 0, ecpri_hdr_cfg_file: ecpri_hdr_cfg.yaml}
  
