# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

aerial_sdk_version: 25-3-cubb
l2adapter_filename: l2_adapter_config_P5G_R750.yaml
aerial_metrics_backend_address: 127.0.0.1:8081

# CPU core shared by all low-priority threads
low_priority_core: 17
enable_ptp_svc_monitoring: 0
ptp_rms_threshold: 20 #ns
nic_tput_alert_threshold_mbps: 85000

cuphydriver_config:
  standalone: 0
  validation: 0
  num_slots: 8
  profiler_sec: 0
  log_level: DBG
  dpdk_thread: 17
  dpdk_verbose_logs: 0
  accu_tx_sched_res_ns: 500
  accu_tx_sched_disable: 0
  fh_stats_dump_cpu_core: 17
  pdump_client_thread: -1
  mps_sm_pusch: 108
  mps_sm_pucch: 16
  mps_sm_prach: 16
  mps_sm_pdsch: 82
  mps_sm_pdcch: 28
  mps_sm_pbch: 14
  mps_sm_srs: 16
  pdsch_fallback: 0
  dpdk_file_prefix: cuphycontroller
  pusch_forcedNumCsi2Bits: 0
  nics:
    - nic: '0000:cc:00.0'
      mtu: 1514
      cpu_mbufs: 196608
      uplane_tx_handles: 64
      txq_size: 8192
      rxq_size: 16384
      gpu: 0
    - nic: '0000:cc:00.1'
      mtu: 1514
      cpu_mbufs: 196608
      uplane_tx_handles: 64
      txq_size: 8192
      rxq_size: 16384
      gpu: 0
  cus_port_failover: 0
  gpus:
    - 0
    # Set GPUID to the GPU sharing the PCIe switch as NIC
    # run nvidia-smi topo -m to find out which GPU
  workers_ul:
    - 5
    - 7
  workers_dl:
    - 9
    - 11
    - 13
  workers_sched_priority: 95
  prometheus_thread: -1
  start_section_id_srs: 3072
  start_section_id_prach: 2048
  enable_ul_cuphy_graphs: 1
  enable_dl_cuphy_graphs: 1
  # Both RF and eLSU eCPRI configs
  ul_order_timeout_cpu_ns: 4000000
  ul_order_timeout_gpu_ns: 3000000
  cplane_disable: 0
  gpu_init_comms_dl: 1
  cell_group: 1
  cell_group_num: 4
  pusch_sinr: 1
  pusch_rssi: 1
  pusch_tdi: 0
  pusch_cfo: 0
  pusch_dftsofdm: 0
  pusch_to:  0
  pusch_select_eqcoeffalgo: 1
  pusch_tbsizecheck: 1
  enable_cpu_task_tracing: 0
  enable_compression_tracing: 0
  enable_prepare_tracing: 0
  enable_dl_cqe_tracing: 0
  mMIMO_enable: 0
  pusch_forcedNumCsi2Bits: 0
  enable_srs: 0
  mCh_segment_proc_enable: 0
  pusch_aggr_per_ctx: 3
  prach_aggr_per_ctx: 2
  pucch_aggr_per_ctx: 4
  srs_aggr_per_ctx: 3
  ul_input_buffer_per_cell: 10
  ul_input_buffer_per_cell_srs: 6
  max_ru_unhealthy_ul_slots: 100
  srs_chest_algo_type: 0
  srs_chest_tol2_normalization_algo_type: 1
  srs_chest_tol2_constant_scaler: 32768.0
  bfw_power_normalization_alg_selector: 1
  total_num_srs_chest_buffers: 6144
  send_static_bfw_wt_all_cplane: 1
  dlc_bfw_enable_divide_per_cell: 0
  ulc_bfw_enable_divide_per_cell: 0
  #static beam id range
  static_beam_id_start: 1
  static_beam_id_end: 16527
  #dynamic beam id range
  dynamic_beam_id_start: 16528 #Dynamic beam ID start should be after static beam ID end
  dynamic_beam_id_end: 32767 #15bit max value
  notify_ul_harq_buffer_release: 0
  cells:
    - name: O-RU 0
      cell_id: 1
      ru_type: 3
      # set to 00:00:00:00:00:00 to use the MAC address of the NIC port to use
      src_mac_addr: 00:00:00:00:00:00
      dst_mac_addr: 22:04:9B:9E:27:A1 # eCPRI cell #1 or 
      nic: '0000:cc:00.0'
      vlan: 2
      pcp: 7
      txq_count_uplane: 1
      eAxC_id_ssb_pbch: [0, 8, 1, 9]
      eAxC_id_pdcch: [0, 8, 1, 9]
      eAxC_id_pdsch: [0, 8, 1, 9]
      eAxC_id_csirs: [0, 8, 1, 9]
      eAxC_id_pusch: [0, 8, 1, 9]
      eAxC_id_pucch: [0, 8, 1, 9]
      eAxC_id_srs: [2, 3, 4, 5]
      eAxC_id_prach: [7, 15, 6, 14]
      dl_iq_data_fmt: {comp_meth: 1, bit_width: 14}
      ul_iq_data_fmt: {comp_meth: 1, bit_width: 14}
      section_3_time_offset: 484
      fs_offset_dl: 0
      exponent_dl: 4
      ref_dl: 0
      fs_offset_ul: 0
      exponent_ul: 4
      max_amp_ul: 65504
      mu: 1
      T1a_max_up_ns: 345000
      T1a_max_cp_ul_ns: 316000
      Ta4_min_ns: 50000
      Ta4_max_ns: 331000
      Tcp_adv_dl_ns: 125000
      ul_u_plane_tx_offset_ns: 280000
      fh_len_range: 0
      pusch_prb_stride: 273
      prach_prb_stride: 12
      srs_prb_stride: 273
      pusch_ldpc_max_num_itr_algo_type: 1
      pusch_fixed_max_num_ldpc_itrs: 10
      pusch_ldpc_early_termination: 0
      pusch_ldpc_algo_index: 0
      pusch_ldpc_flags: 2
      pusch_ldpc_use_half: 1
      ul_gain_calibration: 48.68
      lower_guard_bw: 845
      tv_pusch: cuPhyChEstCoeffs.h5
    - name: O-RU 1
      cell_id: 2
      ru_type: 3
      # set to 00:00:00:00:00:00 to use the MAC address of the NIC port to use
      src_mac_addr: 00:00:00:00:00:00
      dst_mac_addr: 22:04:9B:9E:27:A2 # eCPRI cell #2
      nic: '0000:cc:00.0'
      vlan: 3
      pcp: 7
      txq_count_uplane: 1
      eAxC_id_ssb_pbch: [0, 8, 1, 9]
      eAxC_id_pdcch: [0, 8, 1, 9]
      eAxC_id_pdsch: [0, 8, 1, 9]
      eAxC_id_csirs: [0, 8, 1, 9]
      eAxC_id_pusch: [0, 8, 1, 9]
      eAxC_id_pucch: [0, 8, 1, 9]
      eAxC_id_srs: [2, 3, 4, 5]
      eAxC_id_prach: [7, 15, 6, 14]
      dl_iq_data_fmt: {comp_meth: 1, bit_width: 14}
      ul_iq_data_fmt: {comp_meth: 1, bit_width: 14}
      section_3_time_offset: 484
      fs_offset_dl: 0
      exponent_dl: 4
      ref_dl: 0
      fs_offset_ul: 0
      exponent_ul: 4
      max_amp_ul: 65504
      mu: 1
      T1a_max_up_ns: 345000
      T1a_max_cp_ul_ns: 316000
      Ta4_min_ns: 50000
      Ta4_max_ns: 331000
      Tcp_adv_dl_ns: 125000
      ul_u_plane_tx_offset_ns: 280000
      fh_len_range: 0
      pusch_prb_stride: 273
      prach_prb_stride: 12
      srs_prb_stride: 273
      pusch_ldpc_max_num_itr_algo_type: 1
      pusch_fixed_max_num_ldpc_itrs: 10
      pusch_ldpc_early_termination: 0
      pusch_ldpc_algo_index: 0
      pusch_ldpc_flags: 2
      pusch_ldpc_use_half: 1
      ul_gain_calibration: 48.68
      lower_guard_bw: 845
      tv_pusch: cuPhyChEstCoeffs.h5
    - name: O-RU 2
      cell_id: 3
      ru_type: 3
      # set to 00:00:00:00:00:00 to use the MAC address of the NIC port to use
      src_mac_addr: 00:00:00:00:00:00
      dst_mac_addr: 22:04:9B:9E:27:A3 # eCPRI cell #3
      nic: '0000:cc:00.1'
      vlan: 4
      pcp: 7
      txq_count_uplane: 1
      eAxC_id_ssb_pbch: [0, 8, 1, 9]
      eAxC_id_pdcch: [0, 8, 1, 9]
      eAxC_id_pdsch: [0, 8, 1, 9]
      eAxC_id_csirs: [0, 8, 1, 9]
      eAxC_id_pusch: [0, 8, 1, 9]
      eAxC_id_pucch: [0, 8, 1, 9]
      eAxC_id_srs: [2, 3, 4, 5]
      eAxC_id_prach: [7, 15, 6, 14]
      dl_iq_data_fmt: {comp_meth: 1, bit_width: 14}
      ul_iq_data_fmt: {comp_meth: 1, bit_width: 14}
      section_3_time_offset: 484
      fs_offset_dl: 0
      exponent_dl: 4
      ref_dl: 0
      fs_offset_ul: 0
      exponent_ul: 4
      max_amp_ul: 65504
      mu: 1
      T1a_max_up_ns: 345000
      T1a_max_cp_ul_ns: 316000
      Ta4_min_ns: 50000
      Ta4_max_ns: 331000
      Tcp_adv_dl_ns: 125000
      ul_u_plane_tx_offset_ns: 280000
      fh_len_range: 0
      pusch_prb_stride: 273
      prach_prb_stride: 12
      srs_prb_stride: 273
      pusch_ldpc_max_num_itr_algo_type: 1
      pusch_fixed_max_num_ldpc_itrs: 10
      pusch_ldpc_early_termination: 0
      pusch_ldpc_algo_index: 0
      pusch_ldpc_flags: 2
      pusch_ldpc_use_half: 1
      ul_gain_calibration: 48.68
      lower_guard_bw: 845
      tv_pusch: cuPhyChEstCoeffs.h5
    - name: O-RU 3
      cell_id: 4
      ru_type: 3
      # set to 00:00:00:00:00:00 to use the MAC address of the NIC port to use
      src_mac_addr: 00:00:00:00:00:00
      dst_mac_addr: 22:04:9B:9E:27:A4 # eCPRI cell #4
      nic: '0000:cc:00.1'
      vlan: 5
      pcp: 7
      txq_count_uplane: 1
      eAxC_id_ssb_pbch: [0, 8, 1, 9]
      eAxC_id_pdcch: [0, 8, 1, 9]
      eAxC_id_pdsch: [0, 8, 1, 9]
      eAxC_id_csirs: [0, 8, 1, 9]
      eAxC_id_pusch: [0, 8, 1, 9]
      eAxC_id_pucch: [0, 8, 1, 9]
      eAxC_id_srs: [2, 3, 4, 5]
      eAxC_id_prach: [7, 15, 6, 14]
      dl_iq_data_fmt: {comp_meth: 1, bit_width: 14}
      ul_iq_data_fmt: {comp_meth: 1, bit_width: 14}
      section_3_time_offset: 484
      fs_offset_dl: 0
      exponent_dl: 4
      ref_dl: 0
      fs_offset_ul: 0
      exponent_ul: 4
      max_amp_ul: 65504
      mu: 1
      T1a_max_up_ns: 345000
      T1a_max_cp_ul_ns: 316000
      Ta4_min_ns: 50000
      Ta4_max_ns: 331000
      Tcp_adv_dl_ns: 125000
      ul_u_plane_tx_offset_ns: 280000
      fh_len_range: 0
      pusch_prb_stride: 273
      prach_prb_stride: 12
      srs_prb_stride: 273
      pusch_ldpc_max_num_itr_algo_type: 1
      pusch_fixed_max_num_ldpc_itrs: 10
      pusch_ldpc_early_termination: 0
      pusch_ldpc_algo_index: 0
      pusch_ldpc_flags: 2
      pusch_ldpc_use_half: 1
      ul_gain_calibration: 48.68
      lower_guard_bw: 845
      tv_pusch: cuPhyChEstCoeffs.h5
    - name: O-RU 4
      cell_id: 5
      ru_type: 3
      # set to 00:00:00:00:00:00 to use the MAC address of the NIC port to use
      src_mac_addr: 00:00:00:00:00:00
      dst_mac_addr: 22:04:9B:9E:27:A5 # eCPRI cell #5
      nic: '0000:cc:00.0'
      vlan: 6
      pcp: 7
      txq_count_uplane: 1
      eAxC_id_ssb_pbch: [0, 8, 1, 9]
      eAxC_id_pdcch: [0, 8, 1, 9]
      eAxC_id_pdsch: [0, 8, 1, 9]
      eAxC_id_csirs: [0, 8, 1, 9]
      eAxC_id_pusch: [0, 8, 1, 9]
      eAxC_id_pucch: [0, 8, 1, 9]
      eAxC_id_srs: [2, 3, 4, 5]
      eAxC_id_prach: [7, 15, 6, 14]
      dl_iq_data_fmt: {comp_meth: 1, bit_width: 14}
      ul_iq_data_fmt: {comp_meth: 1, bit_width: 14}
      section_3_time_offset: 484
      fs_offset_dl: 0
      exponent_dl: 4
      ref_dl: 0
      fs_offset_ul: 0
      exponent_ul: 4
      max_amp_ul: 65504
      mu: 1
      T1a_max_up_ns: 345000
      T1a_max_cp_ul_ns: 316000
      Ta4_min_ns: 50000
      Ta4_max_ns: 331000
      Tcp_adv_dl_ns: 125000
      ul_u_plane_tx_offset_ns: 280000
      fh_len_range: 0
      pusch_prb_stride: 273
      prach_prb_stride: 12
      srs_prb_stride: 273
      pusch_ldpc_max_num_itr_algo_type: 1
      pusch_fixed_max_num_ldpc_itrs: 10
      pusch_ldpc_early_termination: 0
      pusch_ldpc_algo_index: 0
      pusch_ldpc_flags: 2
      pusch_ldpc_use_half: 1
      ul_gain_calibration: 48.68
      lower_guard_bw: 845
      tv_pusch: cuPhyChEstCoeffs.h5
    - name: O-RU 5
      cell_id: 6
      ru_type: 3
      # set to 00:00:00:00:00:00 to use the MAC address of the NIC port to use
      src_mac_addr: 00:00:00:00:00:00
      dst_mac_addr: 22:04:9B:9E:27:A6 # eCPRI cell #6
      nic: '0000:cc:00.0'
      vlan: 7
      pcp: 7
      txq_count_uplane: 1
      eAxC_id_ssb_pbch: [0, 8, 1, 9]
      eAxC_id_pdcch: [0, 8, 1, 9]
      eAxC_id_pdsch: [0, 8, 1, 9]
      eAxC_id_csirs: [0, 8, 1, 9]
      eAxC_id_pusch: [0, 8, 1, 9]
      eAxC_id_pucch: [0, 8, 1, 9]
      eAxC_id_srs: [2, 3, 4, 5]
      eAxC_id_prach: [7, 15, 6, 14]
      dl_iq_data_fmt: {comp_meth: 1, bit_width: 14}
      ul_iq_data_fmt: {comp_meth: 1, bit_width: 14}
      section_3_time_offset: 484
      fs_offset_dl: 0
      exponent_dl: 4
      ref_dl: 0
      fs_offset_ul: 0
      exponent_ul: 4
      max_amp_ul: 65504
      mu: 1
      T1a_max_up_ns: 345000
      T1a_max_cp_ul_ns: 316000
      Ta4_min_ns: 50000
      Ta4_max_ns: 331000
      Tcp_adv_dl_ns: 125000
      ul_u_plane_tx_offset_ns: 280000
      fh_len_range: 0
      pusch_prb_stride: 273
      prach_prb_stride: 12
      srs_prb_stride: 273
      pusch_ldpc_max_num_itr_algo_type: 1
      pusch_fixed_max_num_ldpc_itrs: 10
      pusch_ldpc_early_termination: 0
      pusch_ldpc_algo_index: 0
      pusch_ldpc_flags: 2
      pusch_ldpc_use_half: 1
      ul_gain_calibration: 48.68
      lower_guard_bw: 845
      tv_pusch: cuPhyChEstCoeffs.h5
    - name: O-RU 6
      cell_id: 7
      ru_type: 3
      # set to 00:00:00:00:00:00 to use the MAC address of the NIC port to use
      src_mac_addr: 00:00:00:00:00:00
      dst_mac_addr: 22:04:9B:9E:27:A7 # eCPRI cell #7
      nic: '0000:cc:00.1'
      vlan: 8
      pcp: 7
      txq_count_uplane: 1
      eAxC_id_ssb_pbch: [0, 8, 1, 9]
      eAxC_id_pdcch: [0, 8, 1, 9]
      eAxC_id_pdsch: [0, 8, 1, 9]
      eAxC_id_csirs: [0, 8, 1, 9]
      eAxC_id_pusch: [0, 8, 1, 9]
      eAxC_id_pucch: [0, 8, 1, 9]
      eAxC_id_srs: [2, 3, 4, 5]
      eAxC_id_prach: [7, 15, 6, 14]
      dl_iq_data_fmt: {comp_meth: 1, bit_width: 14}
      ul_iq_data_fmt: {comp_meth: 1, bit_width: 14}
      section_3_time_offset: 484
      fs_offset_dl: 0
      exponent_dl: 4
      ref_dl: 0
      fs_offset_ul: 0
      exponent_ul: 4
      max_amp_ul: 65504
      mu: 1
      T1a_max_up_ns: 345000
      T1a_max_cp_ul_ns: 316000
      Ta4_min_ns: 50000
      Ta4_max_ns: 331000
      Tcp_adv_dl_ns: 125000
      ul_u_plane_tx_offset_ns: 280000
      fh_len_range: 0
      pusch_prb_stride: 273
      prach_prb_stride: 12
      srs_prb_stride: 273
      pusch_ldpc_max_num_itr_algo_type: 1
      pusch_fixed_max_num_ldpc_itrs: 10
      pusch_ldpc_early_termination: 0
      pusch_ldpc_algo_index: 0
      pusch_ldpc_flags: 2
      pusch_ldpc_use_half: 1
      ul_gain_calibration: 48.68
      lower_guard_bw: 845
      tv_pusch: cuPhyChEstCoeffs.h5
    - name: O-RU 7
      cell_id: 8
      ru_type: 3
      # set to 00:00:00:00:00:00 to use the MAC address of the NIC port to use
      src_mac_addr: 00:00:00:00:00:00
      dst_mac_addr: 22:04:9B:9E:27:A8 # eCPRI cell #8
      nic: '0000:cc:00.1'
      vlan: 9
      pcp: 7
      txq_count_uplane: 1
      eAxC_id_ssb_pbch: [0, 8, 1, 9]
      eAxC_id_pdcch: [0, 8, 1, 9]
      eAxC_id_pdsch: [0, 8, 1, 9]
      eAxC_id_csirs: [0, 8, 1, 9]
      eAxC_id_pusch: [0, 8, 1, 9]
      eAxC_id_pucch: [0, 8, 1, 9]
      eAxC_id_srs: [2, 3, 4, 5]
      eAxC_id_prach: [7, 15, 6, 14]
      dl_iq_data_fmt: {comp_meth: 1, bit_width: 14}
      ul_iq_data_fmt: {comp_meth: 1, bit_width: 14}
      section_3_time_offset: 484
      fs_offset_dl: 0
      exponent_dl: 4
      ref_dl: 0
      fs_offset_ul: 0
      exponent_ul: 4
      max_amp_ul: 65504
      mu: 1
      T1a_max_up_ns: 345000
      T1a_max_cp_ul_ns: 316000
      Ta4_min_ns: 50000
      Ta4_max_ns: 331000
      Tcp_adv_dl_ns: 125000
      ul_u_plane_tx_offset_ns: 280000
      fh_len_range: 0
      pusch_prb_stride: 273
      prach_prb_stride: 12
      srs_prb_stride: 273
      pusch_ldpc_max_num_itr_algo_type: 1
      pusch_fixed_max_num_ldpc_itrs: 10
      pusch_ldpc_early_termination: 0
      pusch_ldpc_algo_index: 0
      pusch_ldpc_flags: 2
      pusch_ldpc_use_half: 1
      ul_gain_calibration: 48.68
      lower_guard_bw: 845
      tv_pusch: cuPhyChEstCoeffs.h5
