# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
aerial_sdk_version: 25-3-cubb
#gnb_module
msg_type: scf_5g_fapi
phy_class: scf_5g_fapi
slot_advance: 3

# tick_generator_mode: 0 - poll + sleep; 1 - sleep; 2 - timer_fd
tick_generator_mode: 1

# Allowed maximum latency of SLOT FAPI messages which send from L2 to L1. Unit: slot
allowed_fapi_latency: 0

# Allowed tick interval error. Unit: us
allowed_tick_error: 10

timer_thread_config:
  name: timer_thread
  cpu_affinity: 9
  sched_priority: 99
message_thread_config:
  name: msg_processing
  #core assignment
  cpu_affinity: 10
  # thread priority
  sched_priority: 95
# Lowest TTI for Ticking
mu_highest: 1
dl_tb_loc: 1
timer_thread_wakeup_threshold: 20000
l2a_allowed_latency: 100000
enableTickDynamicSfnSlot: 0
staticPucchSlotNum: 0
staticPuschSlotNum: 0
staticPdcchSlotNum: 0
staticPdschSlotNum: 0
staticCsiRsSlotNum: 0
staticSsbPcid: -1
staticSsbSFN: -1
# SHM IPC sync mode: 0 - sync per cell, 1 - sync per TTI
ipc_sync_mode: 0
cell_group: 1
enable_precoding: 1
enable_beam_forming: 1

prepone_h2d_copy: 0
pucch_dtx_thresholds: [-100.0, -100.0, 1.0, 1.0, -100.0]
pusch_dtx_thresholds: 1.0
# Duplicate the cell configs at the first message
duplicate_config_all_cells: 0

instances:
  # PHY 0
  -
    name: scf_gnb_configure_module_0_instance_0
  -
    name: scf_gnb_configure_module_0_instance_1
  -
    name: scf_gnb_configure_module_0_instance_2
  -
    name: scf_gnb_configure_module_0_instance_3
  -
    name: scf_gnb_configure_module_0_instance_4
  -
    name: scf_gnb_configure_module_0_instance_5
  -
    name: scf_gnb_configure_module_0_instance_6
  -
    name: scf_gnb_configure_module_0_instance_7
  -
    name: scf_gnb_configure_module_0_instance_8
  -
    name: scf_gnb_configure_module_0_instance_9
  -
    name: scf_gnb_configure_module_0_instance_10
  -
    name: scf_gnb_configure_module_0_instance_11
  -
    name: scf_gnb_configure_module_0_instance_12
  -
    name: scf_gnb_configure_module_0_instance_13
  -
    name: scf_gnb_configure_module_0_instance_14
  -
    name: scf_gnb_configure_module_0_instance_15

# Config dedicated yaml file for nvipc. Example: nvipc_multi_instances.yaml
nvipc_config_file: null

# Transport settings for nvIPC
transport:
  type: shm
  shm_config:
    primary: 1
    prefix: nvipc
    cuda_device_id: 0
    ring_len: 8192
    mempool_size:
      cpu_msg:
        buf_size: 15000
        pool_len: 4096
      cpu_data:
        buf_size: 576000
        pool_len: 1024
      cpu_large:
        buf_size: 4096000
        pool_len: 64
      cuda_data:
        buf_size: 307200
        pool_len: 0
      gpu_data:
        buf_size: 576000
        pool_len: 0
  app_config:
    grpc_forward: 0 # Forward nvipc message to a "<prefix>_fw" queue for engineering debug
    debug_timing: 0 # Saving full timestamps of nvipc message states for engineering debug
    pcap_enable: 0 # Enable PCAP logging
    pcap_sync_save: 0 # 0 - Asynchronized saving packets in SHM caching thread; 1 - Synchronized saving packets in caller thread
    pcap_shm_caching_cpu_core: 17 # CPU core of pcap shared memory caching thread
    pcap_file_saving_cpu_core: 17 # CPU core of pcap file saving thread
    pcap_cache_size_bits: 29 # 2^29 = 512MB, size of /dev/shm/${prefix}_pcap
    pcap_file_size_bits: 31 # 2^31 = 2GB, max size of /var/log/aerial/${prefix}_pcap. Requires pcap_file_size_bits > pcap_cache_size_bits.
    pcap_max_data_size: 8000 # Max DL/UL FAPI data size to capture reduce pcap size.
    msg_filter: [] # Example: [0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x80, 0x81, 0x82, 0x83, 0x84, 0x85]
    cell_filter: [] # Example: [0, 1, 2, 3]

...
