# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
aerial_sdk_version: 25-3-cubb
# WAR for limitation that all cells need to be configured at initial
wait_all_cell_config: 1

# Transport settings for nvIPC
transport:
  - transport_id: 0
    phy_cells: [0, 1, 2, 3]
    type: shm
    shm_config:
      prefix: nvipc
      cuda_device_id: -1
      ring_len: 8192
      mempool_size:
        cpu_msg:
          buf_size: 15000
          pool_len: 4096
        cpu_data:
          buf_size: 576000
          pool_len: 1024
        cpu_large:
          buf_size: 4096000
          pool_len: 64
        cuda_data:
          buf_size: 307200
          pool_len: 0
    app_config:
      grpc_forward: 0 # Forward nvipc message to a "<prefix>_fw" queue for engineering debug
      debug_timing: 0 # Saving full timestamps of nvipc message states for engineering debug
      pcap_enable: 0 # Enable PCAP logging
      pcap_sync_save: 0 # 0 - Asynchronized saving packets in SHM caching thread; 1 - Synchronized saving packets in caller thread
      pcap_shm_caching_cpu_core: 18 # CPU core of pcap shared memory caching thread
      pcap_file_saving_cpu_core: 18 # CPU core of pcap file saving thread
      pcap_cache_size_bits: 29 # 2^29 = 512MB, size of /dev/shm/${prefix}_pcap
      pcap_file_size_bits: 31 # 2^31 = 2GB, max size of /var/log/aerial/${prefix}_pcap. Requires pcap_file_size_bits > pcap_cache_size_bits.
      pcap_max_data_size: 8000 # Max DL/UL FAPI data size to capture reduce pcap size.
      msg_filter: [] # Example: [0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x80, 0x81, 0x82, 0x83, 0x84, 0x85]
      cell_filter: [] # Example: [0, 1, 2, 3]

  - transport_id: 1
    phy_cells: [4, 5, 6, 7]
    type: shm
    shm_config:
      prefix: nvipc1
      cuda_device_id: -1
      ring_len: 8192
      mempool_size:
        cpu_msg:
          buf_size: 15000
          pool_len: 4096
        cpu_data:
          buf_size: 576000
          pool_len: 1024
        cpu_large:
          buf_size: 4096000
          pool_len: 64
        cuda_data:
          buf_size: 307200
          pool_len: 0
    app_config:
      grpc_forward: 0 # Forward nvipc message to a "<prefix>_fw" queue for engineering debug
      debug_timing: 0 # Saving full timestamps of nvipc message states for engineering debug
      pcap_enable: 0 # Enable PCAP logging
      pcap_sync_save: 0 # 0 - Asynchronized saving packets in SHM caching thread; 1 - Synchronized saving packets in caller thread
      pcap_shm_caching_cpu_core: 22 # CPU core of pcap shared memory caching thread
      pcap_file_saving_cpu_core: 22 # CPU core of pcap file saving thread
      pcap_cache_size_bits: 29 # 2^29 = 512MB, size of /dev/shm/${prefix}_pcap
      pcap_file_size_bits: 31 # 2^31 = 2GB, max size of /var/log/aerial/${prefix}_pcap. Requires pcap_file_size_bits > pcap_cache_size_bits.
      pcap_max_data_size: 8000 # Max DL/UL FAPI data size to capture reduce pcap size.
      msg_filter: [] # Example: [0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x80, 0x81, 0x82, 0x83, 0x84, 0x85]
      cell_filter: [] # Example: [0, 1, 2, 3]

...
