# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# mMIMO scheduler testbench configuration file
---
# thread core config
L2_SENDER_THREAD_CORE: 8
L2_RECV_THREAD_CORE: 9
cuMAC_WORKER_THREAD_CORE: 5
cuMAC_RECV_THREAD_CORE: 6

# config constants
NUM_TIME_SLOTS: 20
TDD_PATTERN: "SDDSD"
NUM_CELL: 1 # number of cells jointly scheduled by cuMAC
NUM_UE_ANT_PORT: 4 # number of antenna ports per UE
NUM_BS_ANT_PORT: 64 # number of antenna ports per RU
NUM_SRS_UE_PER_CELL: 256 # total number of SRS enabled UEs per cell
NUM_SUBBAND: 4 # number of subbands
NUM_PRG_SAMP_PER_SUBBAND: 1 # number of per-PRG SRS channel estimate samples per subband
NUM_PRG_PER_CELL: 68 # number of PRGs per cell
NUM_SRS_UE_PER_SLOT: 32 # number of SRS UEs scheduled per S-slot
MAX_NUM_UE_SCHEDULED_PER_CELL_TTI: 16 # maximum number of scheduled UEs /cell/TTI
MAX_NUM_UE_FOR_GRP_PER_CELL: 32 # maximum number of UE groups per cell

SRS_CHAN_EST_COEFF_VAR: 1e-6
SCS: 30000

#SLOT_INTERVAL_NS: 500
SLOT_INTERVAL_NS: 1000000000 # Time slot interval in nanoseconds. Set to 1 second for debugging

# CUDA kernel config
NUM_BLOCKS_PER_ROW_CHAN_OR_MAT: 8 # number of blocks per row of channel orthogonality matrix, optimal value is 2 for V1 kernel, 8 for V2 kernel